name: Publish packages

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run build

      - name: publish packages
        run: |
          npm publish --workspaces --access public --verbose
